# --- GUI CONFIGURATION ---
CELL_SIZE = 16
UPDATE_DELAY = 50

# --- WORLD CONFIGURATION ---
WORLD_WIDTH = 60
WORLD_HEIGHT = 45
STARTING_AGENTS = 8
RESOURCE_REGEN_INTERVAL = 15
ANIMAL_SPAWN_INTERVAL = 100
MAX_ANIMALS = 15
MAX_WOLVES = 0 # Wolves are disabled as requested
ANIMAL_MOVE_COOLDOWN = 5 # Ticks between animal moves

# --- AGENT CONFIGURATION ---
AGENT_VIEW_DISTANCE = 10
AGENT_MAX_ENERGY = 200
AGENT_MAX_HYDRATION = 150
AGENT_LOW_ENERGY_THRESHOLD = 50
AGENT_LOW_HYDRATION_THRESHOLD = 40
AGENT_MAX_HEALTH = 100
AGENT_MOVE_COOLDOWN = 2
ENERGY_PER_FOOD = 80
HYDRATION_PER_DRINK = 100
ADULT_AGE_THRESHOLD = 2000
CHILD_WANDER_RADIUS = 5
PREGNANCY_CHANCE = 0.001
PREGNANCY_DURATION = 1500
ACTION_COOLDOWN = 10 # Ticks to wait after some actions

# --- BUILDING & CRAFTING ---
FARM_PRODUCTION_CYCLE = 300
BLACKSMITH_SMELT_TIME = 150
BLACKSMITH_CRAFT_TIME = 200
TOOL_DURABILITY = 50

# --- TERRAIN & PATHING ---
DAY_NIGHT_DURATION = 2400
ROAD_UPDATE_INTERVAL = 100 
ROAD_BUILD_THRESHOLD = 50
PATH_DECAY_RATE = 0.95